# load the assets in order
tile_assets = [
	"/Tiles/Terrain/Grass/grass_05.png",
	"/Tiles/Terrain/Dirt/dirt_06.png",
	"/Tiles/Terrain/Stone/stone_07.png",
]
outline = "/outline.png"
font = "/iosevka-term-ss09-oblique.ttf"